plugin: aws_ec2
regions:
  - eu-west-2

filters:
  tag:Project: devplatform
  tag:Environment: dev
  instance-state-name: running

keyed_groups:
  - key: tags.get('kubernetes.io/cluster/devplatform-dev', 'none')
    prefix: cluster
    separator: "_"
  - key: tags.get('Type', 'unknown')
    prefix: type
    separator: "_"

hostnames:
  - private-dns-name
  - dns-name
  - name

compose:
  ansible_host: private_ip_address
  cluster_name: tags.get('kubernetes.io/cluster/devplatform-dev', 'unknown')
  node_group: tags.get('eks:nodegroup-name', 'unknown')
  instance_type: instance_type