apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: tenant-onboarding
  title: Create New Tenant
  description: Self-service tenant creation with Kubernetes namespace
spec:
  owner: platform-team
  type: service
  parameters:
    - title: Tenant Information
      required:
        - name
        - owner
        - email
      properties:
        name:
          title: Tenant Name
          type: string
          description: Name for the new tenant
        owner:
          title: Owner
          type: string
          description: Tenant owner name
        email:
          title: Email
          type: string
          description: Contact email for the tenant
        description:
          title: Description
          type: string
          description: Brief description of the tenant purpose
  steps:
    - id: create-tenant
      name: Create Tenant
      action: http:backstage:request
      input:
        method: POST
        url: http://localhost:8080/api/v1/tenants
        headers:
          Content-Type: application/json
        body:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          email: ${{ parameters.email }}
          description: ${{ parameters.description }}
  output:
    text:
      - title: Tenant Created
        content: |
          Your tenant **${{ parameters.name }}** has been created successfully!
          
          - Kubernetes namespace: tenant-${{ parameters.name | lower }}
          - Owner: ${{ parameters.owner }}
          - Contact: ${{ parameters.email }}