app:
  title: DevPlatform Portal
  baseUrl: https://portal.iasolutions.co.uk

organization:
  name: DevPlatform

backend:
  baseUrl: https://portal.iasolutions.co.uk
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: https://portal.iasolutions.co.uk
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  reading:
    allow:
      - host: raw.githubusercontent.com
      - host: github.com

proxy:
  endpoints:
    '/platform-api':
      target: 'https://api.iasolutions.co.uk'
      headers:
        Accept: 'application/json'
        Content-Type: 'application/json'

integrations:
  github:
    - host: github.com

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template]
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/org.yaml
    - type: file
      target: ./examples/devplatform-api.yaml
    - type: file
      target: ./examples/devplatform-system.yaml
    - type: file
      target: ./examples/devplatform-template.yaml

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

scaffolder:
  defaultAuthor:
    name: DevPlatform
    email: platform@iasolutions.co.uk
  defaultCommitMessage: 'Initial commit'

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://25A9E2A57845EBAA9E8011ECC61ED398.gr7.eu-west-2.eks.amazonaws.com
          name: devplatform-dev
          authProvider: 'aws'
          